export const stores = [
  {
    storeId: 1324,
    tenantId: "br-us",
    storeName: "BR-345544",
    status: "ACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "ABDR TEXAS GROUP LLC",
    merchantKey: "EMN8",
    city: "Pflugerville",
    street: "1552 FM 685",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78660,

    tax: 0.07,
    phoneNumber: "(512)551-9466",
    timezone: "America/Chicago",
    avgRating: 4.5,
  },
  {
    storeId: 1740,
    tenantId: "br-us",
    storeName: "BR-354395",
    status: "ACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "Round Rock Real Estate LLC",
    merchantKey: "EMN8",
    city: "Austin",
    street: "1610 E Parmer Lane",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78753,

    tax: 0.07,
    phoneNumber: "(512)487-5578",
    timezone: "America/Chicago",
    avgRating: 3.4,
  },
  {
    storeId: 1049,
    tenantId: "br-us",
    storeName: "BR-361670",
    status: "INACTIVE",
    reason: "Other",
    storeIP: "127.0.0.1",
    franchiseNm: "Cool Enterprises, LLC",
    merchantKey: "EMN8",
    city: "Austin",
    street: "12407 N Mo Pac Expy",
    state: "TX",
    country: "USA",
    unit: "Ste 115",
    zipCode: 78758,

    tax: 0.07,
    phoneNumber: "(512)833-8800",
    timezone: "America/Chicago",
    avgRating: 4.5,
  },
  {
    storeId: 1916,
    tenantId: "br-us",
    storeName: "BR-362278",
    status: "ACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "RR Icecreams, LLC",
    merchantKey: "EMN8",
    city: "Round Rock",
    street: "307 W Palm Valley Blvd",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78664,

    tax: 0.07,
    phoneNumber: "(512)310-2431",
    timezone: "America/Chicago",
    avgRating: 4.1,
  },
  {
    storeId: 1051,
    tenantId: "br-us",
    storeName: "BR-347590",
    status: "ACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "Divya Sultani and Yasmine Mandania",
    merchantKey: "EMN8",
    city: "Austin",
    street: "9900 W. Parmer Ln",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78717,

    tax: 0.07,
    phoneNumber: "(512)248-2275",
    timezone: "America/Chicago",
    avgRating: 4.0,
  },
  {
    storeId: 838,
    tenantId: "br-us",
    storeName: "BR-349738",
    status: "ACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "Coffee Action West, LLC",
    merchantKey: "EMN8",
    city: "Cedar Park",
    street: "1851 S Lakeline Blvd",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78613,

    tax: 0.07,
    phoneNumber: "(512)382-5658",
    timezone: "America/Chicago",
    avgRating: 4.1,
  },
  {
    storeId: 721,
    tenantId: "br-us",
    storeName: "BR-346037",
    status: "TEMP-INACTIVE",
    reason: "No Cake Decorator",
    storeIP: "127.0.0.1",
    franchiseNm: "Cup or Cone Confections LLC",
    merchantKey: "EMN8",
    city: "Cedar Park",
    street: "1335 E Whitestone Blvd",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78613,

    tax: 0.07,
    phoneNumber: "(512)986-7593",
    timezone: "America/Chicago",
    avgRating: 3.5,
  },
  {
    storeId: 3465,
    tenantId: "br-us",
    storeName: "BR-364169",
    status: "INACTIVE",
    reason: "Other",
    storeIP: "127.0.0.1",
    franchiseNm: "Priceless Coffee, Inc.",
    merchantKey: "EMN8",
    city: "Elgin",
    street: "200 W U.S. 290",
    state: "TX",
    country: "USA",
    unit: "",
    zipCode: 78621,

    tax: 0.07,
    phoneNumber: "",
    timezone: "America/Chicago",
    avgRating: 4.4,
  },
  {
    storeId: 2247,
    tenantId: "br-us",
    storeName: "BR-349032",
    status: "ACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "Abderrazek Zaafrani",
    merchantKey: "EMN8",
    city: "Georgetown",
    street: "3303 Williams Dr",
    state: "TX",
    country: "USA",
    unit: "Suite 101 Booty's Crossing Center",
    zipCode: 78628,

    tax: 0.07,
    phoneNumber: "(512)863-4478",
    timezone: "America/Chicago",
    avgRating: 4.3,
  },
  {
    storeId: 3689,
    tenantId: "br-us",
    storeName: "BR-365676",
    status: "INACTIVE",
    storeIP: "127.0.0.1",
    franchiseNm: "",
    merchantKey: "EMN8",
    city: "Leander",
    street: "18145 Ronald Reagan Boulevard",
    state: "TX",
    country: "USA",
    unit: "Suite 140",
    zipCode: 78641,

    tax: 0.07,
    phoneNumber: "",
    timezone: "America/Chicago",
    avgRating: 3.9,
  },
  {
    storeId: 108,
    tenantId: "br-us",
    storeName: "BR-360494",
    status: "TEMP-INACTIVE",
    reason: "Other",
    storeIP: "127.0.0.1",
    franchiseNm: "NanoStreamz, LLC",
    merchantKey: "EMN8",
    city: "Austin",
    street: "730 W Stassney Ln",
    state: "TX",
    country: "USA",
    unit: "Ste 155",
    zipCode: 78745,

    tax: 0.07,
    phoneNumber: "(512)444-3049",
    timezone: "America/Chicago",
    avgRating: 3.8,
  },
];
